name: Cache GitHub README Stats

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

# ÂÖÅËÆ∏Ëá™Âä®Êèê‰∫§Âà∞‰ªìÂ∫ì
permissions:
  contents: write

jobs:
  download-assets:
    runs-on: ubuntu-latest
    name: Download assets

    steps:
      - name: Download the stats file
        run: |
          curl 'https://github-readme-stats-one-iota-82.vercel.app/api?username=FrankFeng-23&show_icons=true&role=OWNER,COLLABORATOR,ORGANIZATION_MEMBER&hide_border=true&line_height=24' -o stats.svg

      - name: Download the top languages file
        run: |
          curl 'https://github-readme-stats-one-iota-82.vercel.app/api/top-langs/?username=FrankFeng-23&role=OWNER,COLLABORATOR,ORGANIZATION_MEMBER&layout=compact&hide_border=true&langs_count=8' -o top-langs.svg

      - name: Upload artifacts (v4)
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: |
            stats.svg
            top-langs.svg

  push-assets:
    runs-on: ubuntu-latest
    name: Push assets
    needs: [download-assets]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download artifacts (v4)
        uses: actions/download-artifact@v4
        with:
          name: assets
          path: assets

      - name: Commit updated assets
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(assets): update cached GRS files"
          branch: main
          commit_user_name: "github-readme-stats ü§ñ"
          commit_user_email: actions@github.com
          commit_author: "github-readme-stats ü§ñ <actions@github.com>"
